version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: psql_pass # Установите свой пароль
      POSTGRES_USER: master_user         # Установите своего пользователя
      POSTGRES_DB: master_db             # Установите имя вашей базы данных
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data  # Монтирование папки для данных
