version: '3.1'

services:
  db:
    image: my_custom_postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
    environment:
      POSTGRES_PASSWORD: psql_pass
      POSTGRES_USER: master_user
      POSTGRES_DB: master_db
      ROLE: master
